use_frameworks!

platform :ios, '9.0'

target 'YWKeyboardKit_Example' do
  pod 'YWKeyboardKit', :path => '../'
#   pod 'YWKeyboardKit/LicensePlate', :path => '../'
#   pod 'YWKeyboardKit/InputToolbar', :path => '../'
#   pod 'YWKeyboardKit/IdCard', :path => '../'
#   pod 'YWKeyboardKit/NumPad', :path => '../'
  target 'YWKeyboardKit_Tests' do
    inherit! :search_paths

    
  end
end
